From clouden90/1d_mom6_cobalt:v0.1

SHELL ["/bin/bash","-c"]

USER builder

COPY --chown=builder:builder . /opt/MOM6_OBGC_examples

WORKDIR /opt/datasets/OceanBGC_dataset

RUN wget https://gfdl-med.s3.amazonaws.com/OceanBGC_dataset/COBALT_2023_10_spinup_2003_subset.nc

WORKDIR /opt/MOM6_OBGC_examples/builds

RUN /opt/MOM6_OBGC_examples/builds/linux-build.bash -m docker -p linux-gnu -t prod -f mom6sis2

WORKDIR /opt/MOM6_OBGC_examples/exps

RUN ln -fs /opt/datasets ./

WORKDIR /opt/MOM6_OBGC_examples/exps/OM4.single_column.COBALT.p4

RUN mpirun -np 1 /opt/MOM6_OBGC_examples/builds/build/docker-linux-gnu/ocean_ice/prod/MOM6SIS2
