name: basic tests
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: lscgpu50
    steps:
      - run: module load git; which git
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - run: pwd
      - run: ls src/FMS; ls build
